name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to my Project, thank you for reporting an issue, I will work to fix it as soon as possible!' first issue"
        pr-message: "Welcome to my Project, thank you for submitting a pull request!' first pull request"
